### ISSUE TITLE
MVP Feature: User can create an event at a location with event details

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an event at a location with event details

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click a button to bring up a form to fill out regarding an event, once filled out the user can click another button to 'create' the event

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/132997894-cb656d56-22a3-45a1-87cd-e16a2905ffba.png)
![image](https://user-images.githubusercontent.com/85271794/132997902-d4e11a69-1cb2-4a1b-af8e-6fb7a3ec195e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle POST requests to the database to push newly created events into the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to make the navbar for the home page (header in desktop, footer in mobile)
- [x] In the navbar add a home icon and a new icon
- [x] In the body create a form component
- [x] Text input for Event Name
- [x] Header for Location
- [x] Location input via GoogleMaps API
- [x] Header for Date
- [x] Date input
- [x] Header for Description
- [x] Description textarea
- [x] Header for Picture
- [x] Choosefile input for image

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
