### ISSUE TITLE
MVP Feature: User can view events

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view events on a home page if there are events to be viewed

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click on a button to go to their home page which will show events. They will also be able to click on the listings to reveal the full details

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/132397538-9693dd7d-ce06-4e34-9247-e73979724c30.png)
![image](https://user-images.githubusercontent.com/85271794/132397480-ee62fcc2-1c1e-4966-ae1e-8be0c2489da4.png)
![image](https://user-images.githubusercontent.com/85271794/132397504-191737a7-29bb-4a0b-bafa-84cb2de8e487.png)
![image](https://user-images.githubusercontent.com/85271794/132397571-55035f0b-674c-49c1-81ff-7ad46538eab7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET requests from the database to pull event information (name, location, date/time, description, image)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to view the events (ul with li)
- [x] If no events, display 'You have no events'
- [x] If events returned, show page with events
- [x] Page to view events will include name for each li
- [x] Page to view events will include location each li
- [x] Page to view events will include date/time each li
- [x] Page to view events will include image each li
- [x] If li is clicked on, reveal a new page
- [x] New page will only have information on the li that was clicked on with an additional section including the description

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
