### ISSUE TITLE
MVP Feature: User can view events on a map

### ISSUE THREAD

**Issue by hsu-isaac** [hsu-isaac/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view events on a map

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on a tab button to open the map page where they will be able to see pins at the locations of events they are invited to. Users can click on the pin to reveal information about the event

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85271794/132402807-517411db-9d66-41aa-b1e6-3f0fd1621a7c.png)
![image](https://user-images.githubusercontent.com/85271794/132402821-112c8a12-4cee-47ba-841b-92383e3bdc2c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a class component to display a map
- [x] Make fetch request to call all events into the class state
- [x] For each event within the state object, create a marker at the location
- [x] Make an onClick function for each marker to reveal an information window containing the other information on the event
- [x] ^event name
- [x] ^event image
- [x] ^event date/time
- [x] ^event description

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
